version: '3'

services:
  db_test:
    image: postgres
    ports:
      - 5433:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data/pgdata
  eventstore_test:
    image: eventstore/eventstore:release-5.0.8
    ports:
      - 2114:2113
      - 1114:1113
    restart: always
