version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data/pgdata
  eventstore:
    image: eventstore/eventstore:release-5.0.8
    ports:
      - 2113:2113
      - 1113:1113
    restart: always
